version: "3"
services:

  app:
    restart: always
    build: ./app
    ports:
      - 3000:80

  api:
    restart: always
    build: ./backend
    ports:
      - 8080:8080
    environment:
      - MONGO_DB_ADDR=mongodb
      - MONGO_DB_PORT=27017
    links:
      - service-test

  mongodb:
    restart: always
    image: mongodb:latest
    volumes:
      - mongodb_volume:/data/db