version: "3"
services:
  reverce-proxy: # используем nginx как reverse proxy сервер
    image: nginx:latest
    ports: # Пробрасываем порты 80 для http и 443 для https
      - 80:80
      - 443:443
    container_name: proxy_nginx
    depends_on: # Выраженная зависимость между службами: запустит службы в порядке зависимости и даст доступы как links
      - app
    volumes:
      - ./reverce-proxy/nginx.conf:/etc/nginx/nginx.conf # Используем свой nginx конфиг, он заменит дефолтный в контейнере
      - ./logs:/var/log/nginx/                           # Монтируем папку с логами на хост машину для более удобного доступа
  app:
    container_name: app
    build: ./app
    ports:
      - 3000:3000