version: "3"
services:
  service-test:
    build: ./service-test
    ports:
      - 5000:5000
  api:
    build: backend
    ports:
      - 8080:8080
    environment:
      HOST_SERVICE_TEST: http://service-test:5000/
    links:
      - service-test
  frontend:
    build: app
    ports:
      - 80:80